### ISSUE TITLE
New gitter release is out, fixes security issue

### ISSUE THREAD

**Issue by gsalgado** [snapcrafters/gitter-desktop#2]
Can we haz a new snap for it? http://blog.gitter.im/2018/06/11/gitter-token-leak-security-issue-notification/

**Comment by popey** [comment]
[Building](https://launchpad.net/~build.snapcraft.io/+snap/47203fbfd081423bcc297dd97ef1448f-xenial/+build/245581)!

Edit: Fixed link :)

**Comment by popey** [comment]
That build failed due to upstream having moved to gtk3. Have bumped a new build which should fix it.

**Comment by popey** [comment]
Apologies for the delay, the latest release is now in the stable channel.
